spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  application:
    name: store
  datasource:
    url: jdbc:mysql://localhost:3306/store_api?createDatabaseIfNotExist=true
    username: sakkol
    password: sakkol123
  jpa:
    show-sql: true
  profiles:
    active:
  jwt:
    secret: o4qWeOSCLqYBtuTxBh1xTrV95FabYnNzRmgPstzb7QSrYRCPm10JXfICVpuh4nvva6fR6rXdG86pAkupZFCPJw==
    accessTokenExpiration: 900
    refreshTokenExpiration: 604800
server:
  port: 8080
stripe:
  secretKey: ${STRIPE_SECRET_KEY:}
  publicKey: ${STRIPE_PUBLIC_KEY:}
  webhookKey: ${STRIPE_WEBHOOK_KEY:}
client:
  url: http://localhost3000