spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  application:
    name: store
  datasource:
    url: jdbc:mysql://localhost:3306/store_api?createDatabaseIfNotExist=true
    username: sakkol
    password: sakkol123
  jpa:
    show-sql: true
  profiles:
    active:
  jwt:
    secret: ${JWT_SECRET:}
    accessTokenExpiration: 900
    refreshTokenExpiration: 604800
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:}
            client-secret: ${GOOGLE_SECRET_ID:}
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            scope:
              - email
              - profile
          github:
            client-id: ${GITHUB_CLIENT_ID:}
            client-secret: ${GITHUB_SECRET_ID:}
            redirect-uri: http://localhost:8080/login/oauth2/code/github
            scope:
              - email
              - profile
server:
  port: 8080
stripe:
  secretKey: ${STRIPE_SECRET_KEY:}
  publicKey: ${STRIPE_PUBLIC_KEY:}
  webhookKey: ${STRIPE_WEBHOOK_KEY:}
client:
  url: http://localhost3000